apiVersion: apps/v1
kind: Deployment
metadata:
  name: jarvistemplate
  labels:
    app: jarvistemplate
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jarvistemplate
      
  template:
    metadata:
      labels:
        app: jarvistemplate
        tier: jarvistemplate
    spec:
      containers:
        - name: jarvistemplate
          image: jarvistrendz/jarvistemplate:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
            name: jarvistemplate
      ports:
        - port: 5000
          targetPort: 5000
      selector:
            app: jarvistemplate
            tier: jarvistemplate
            type: LoadBalancer

